/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => InlineRenamePlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var InlineRenamePlugin = class extends import_obsidian.Plugin {
  activeFilePath = null;
  activeFileSetAt = 0;
  isRenaming = false;
  renamingPath = null;
  async onload() {
    this.registerEvent(
      this.app.workspace.on("active-leaf-change", (_leaf) => {
        const file = this.app.workspace.getActiveFile();
        const newPath = file?.path ?? null;
        this.activeFilePath = newPath;
        this.activeFileSetAt = Date.now();
        if (this.isRenaming && newPath !== this.renamingPath) {
          this.cancelRename();
        }
      })
    );
    document.addEventListener("click", this.onClick, true);
    this.register(() => {
      document.removeEventListener("click", this.onClick, true);
    });
    console.log("[ARA] loaded. Active file:", this.app.workspace.getActiveFile()?.path ?? "(none)");
  }
  onunload() {
    console.log("[ARA] unloaded");
  }
  // ── Click handler (capture phase) ─────────────────────────────
  onClick = (evt) => {
    if (this.isRenaming) return;
    const target = evt.target;
    const titleRow = target.closest(".tree-item-self.nav-file-title") ?? target.closest(".nav-file-title");
    if (!titleRow) return;
    const container = titleRow.closest(".tree-item") ?? titleRow.closest(".nav-file");
    if (!container) return;
    const file = this.resolveFile(container, titleRow);
    if (!file) {
      console.log("[ARA] click on file row but resolveFile failed");
      return;
    }
    if (file.path !== this.activeFilePath) {
      console.log("[ARA] not active file. clicked:", file.path, "active:", this.activeFilePath);
      return;
    }
    const elapsed = Date.now() - this.activeFileSetAt;
    if (elapsed < 650) {
      console.log("[ARA] cooldown active:", elapsed, "ms");
      return;
    }
    console.log("[ARA] TRIGGERING RENAME for:", file.path);
    evt.preventDefault();
    evt.stopPropagation();
    evt.stopImmediatePropagation();
    this.startInlineRename(titleRow, file);
  };
  // ── Cancel ongoing rename ──────────────────────────────────────
  cancelRename() {
    this.isRenaming = false;
    this.renamingPath = null;
  }
  // ── Resolve DOM to TFile ───────────────────────────────────────
  resolveFile(container, titleRow) {
    const seen = /* @__PURE__ */ new Set();
    let el = titleRow;
    while (el) {
      if (seen.has(el)) {
        el = el.parentElement;
        continue;
      }
      seen.add(el);
      const path = el.getAttribute("data-path") ?? el.dataset?.path;
      if (path) {
        const abstract = this.app.vault.getAbstractFileByPath(path);
        if (abstract instanceof import_obsidian.TFile) {
          console.log("[ARA] resolved file via data-path:", path);
          return abstract;
        }
        console.log("[ARA] data-path found but file not in vault:", path);
      }
      el = el.parentElement;
    }
    const displayName = titleRow.querySelector(".tree-item-inner")?.textContent?.trim() ?? titleRow.querySelector(".nav-file-title-content")?.textContent?.trim() ?? titleRow.textContent?.trim();
    if (!displayName) return null;
    const files = this.app.vault.getFiles();
    return files.find((f) => f.name === displayName) ?? files.find((f) => f.path === displayName) ?? files.find((f) => f.path.endsWith("/" + displayName)) ?? null;
  }
  // ── Inline rename logic ────────────────────────────────────────
  startInlineRename(titleRow, file) {
    this.isRenaming = true;
    this.renamingPath = file.path;
    const originalName = file.name;
    const ext = file.extension ? "." + file.extension : "";
    const baseName = ext ? originalName.slice(0, -ext.length) : originalName;
    const textEl = titleRow.querySelector(".tree-item-inner") ?? titleRow.querySelector(".nav-file-title-content");
    if (!textEl) return;
    textEl.classList.add("inline-rename-hidden");
    const input = document.createElement("input");
    input.type = "text";
    input.value = originalName;
    input.className = "inline-rename-input";
    input.addEventListener("click", (e) => e.stopPropagation());
    input.addEventListener("mousedown", (e) => e.stopPropagation());
    titleRow.appendChild(input);
    if (baseName && baseName.length > 0) {
      input.setSelectionRange(0, baseName.length);
    } else {
      input.select();
    }
    requestAnimationFrame(() => input.focus());
    const cleanup = () => {
      if (input.parentNode) input.remove();
      textEl.classList.remove("inline-rename-hidden");
      this.isRenaming = false;
      this.renamingPath = null;
    };
    let hasCommitted = false;
    const finishRename = async (newNameRaw) => {
      if (hasCommitted) return;
      hasCommitted = true;
      const newName = newNameRaw.trim();
      cleanup();
      if (!newName || newName === originalName) return;
      let finalName = newName;
      if (ext && !finalName.endsWith(ext)) {
        finalName = finalName + ext;
      }
      const dirPath = file.path.slice(0, -originalName.length);
      const newPath = dirPath + finalName;
      try {
        await this.app.vault.rename(file, newPath);
        console.log(`[ARA] "${originalName}" \u2192 "${finalName}"`);
      } catch (err) {
        console.error("[ARA] rename failed", err);
      }
    };
    input.addEventListener("blur", () => {
      setTimeout(() => finishRename(input.value), 100);
    });
    input.addEventListener("keydown", (e) => {
      if (e.key === "Enter") {
        e.preventDefault();
        finishRename(input.value);
      } else if (e.key === "Escape") {
        e.preventDefault();
        input.value = originalName;
        hasCommitted = true;
        cleanup();
      }
    });
  }
};
